bot:
  name: MP2I

guilds:
  872138069594214410:
    name: Prépas MP2I
    link: https://discord.gg/w4ugrWy84W
    roles:
      "Lycéen":
        id: 872159565741969409
        emoji: berceau
        choice: true
      "MP2I":
        id: 872139011106431016
        emoji: MP2I
        choice: true
      "MPI":
        id: 999760111838970007
        emoji: MPI
        choice: true
      "Ex MPI":
        id: 1132271180485754951
        emoji: ex
        choice: false
      "Intégré":
        id: 872150707250274355
        emoji: ecrous
        choice: true
      "Diplômé":
        id: 1288507548546105354
        emoji: diplome
        choice: true
      "Infiltré":
        id: 872139100805804082
        emoji: ninja
        choice: true
      "Prof":
        id: 872148548211318856
        emoji: livre
        choice: true
      "Référent CPGE":
        id: 983438199823142972
        emoji: contact
        choice: false
      "Référent École":
        id: 1266772126946295828
        emoji: contact
        choice: false
      "Administrateur":
        id: 872138521970901052
        emoji: administration
        choice: false
      "Modérateur":
        id: 934167202746232842
        emoji: marteau
        choice: false
      "Gestion Association":
        id: 1213946755322880081
        emoji: association
        choice: false
      "Association":
        id: 1214155483007557694
        emoji: association
        choice: false
    channels:
      suggestion: 940718694357676042
      log: 1117429400200298558
      website: 911609939728949309

  939262781629276200:
    name: Prépas MP2I [Test]
    link: https://discord.gg/AGtsn9cQ8Z
    roles:
      "Lycéen":
        id: 939262781629276201
        emoji: berceau
        choice: true
      "MP2I":
        id: 939262781629276204
        emoji: MP2I
        choice: true
      "MPI":
        id: 999791743987884202
        emoji: MPI
        choice: true
      "Ex MPI":
        id: 1132271958713704578
        emoji: ex
        choice: false
      "Intégré":
        id: 939262781629276203
        emoji: ecrous
        choice: true
      "Infiltré":
        id: 939262781629276202
        emoji: ninja
        choice: true
      "Diplômé":
        id: 1289586060153589842
        emoji: diplome
        choice: true
      "Prof":
        id: 939262781629276206
        emoji: livre
        choice: true
      "Référent CPGE":
        id: 1119189219215155253
        emoji: contact
        choice: false
      "Référent École":
        id: 1289622142454861834
        emoji: contact
        choice: false
      "Administrateur":
        id: 939262781629276209
        emoji: administration
        choice: false
      "Modérateur":
        id: 939262781629276208
        emoji: marteau
        choice: false
      "Gestion Association":
        id: 1286315335989067816
        emoji: association
        choice: false
      "Association":
        id: 1286315680752209920
        emoji: association
        choice: false
    channels:
      suggestion: 939262782073897053
      log: 1117429934336508005
      website: 939262782342303796
